server:
  port: 8083
spring:
  application:
    name: search-service
  data:
    elasticsearch:
#      cluster-nodes: 10.0.14.166:9300
      cluster-nodes: 192.168.1.100:9300
  jackson:
    default-property-inclusion: non_null
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}